import {
  BookOpenTextIcon,
  CircuitBoard,
  Cpu,
  Database,
  Download,
  Eye,
  FileDown,
  KeyRound,
  LayoutDashboardIcon,
  MessageCirclePlus,
  Palette,
  PencilLine,
  PenSquareIcon,
  Rocket,
  Settings2Icon,
  Trash2,
  User,
  Wand2,
} from "lucide-react";
import { MindSageMark } from "../components/ui/MindSageMark";

export const settingsCommands = [
  // --- Profile ---
  {
    type: "Settings",
    title: "Edit Profile Information",
    icon: User,
    path: "/settings/profile",
    keywords: [
      "settings",
      "profile",
      "edit",
      "update",
      "account",
      "user",
      "info",
      "information",
      "name",
      "username",
      "email",
      "phone",
      "dob",
      "date of birth",
      "details",
      "settings",
      "manage account",
      "change details",
      "preferences",
      "personal",
      "identity",
      "account settings",
    ],
  },
  {
    type: "Settings",
    title: "Change Profile Picture",
    icon: Settings2Icon,
    path: "/settings/profile",
    keywords: [
      "settings",
      "profile",
      "picture",
      "photo",
      "avatar",
      "image",
      "display picture",
      "dp",
      "upload",
      "change photo",
      "update image",
      "set picture",
      "icon",
      "portrait",
      "face",
      "profile image",
      "edit avatar",
    ],
  },
  // --- Themes ---
  {
    type: "Settings",
    title: "Change Theme",
    icon: Palette,
    path: "/settings/colors",
    keywords: [
      "settings",
      "theme",
      "appearance",
      "color",
      "colors",
      "style",
      "look",
      "ui",
      "ux",
      "dark mode",
      "light mode",
      "switch theme",
      "design",
      "palette",
      "skin",
      "mode",
      "background",
      "customize",
      "visuals",
    ],
  },
  // --- Models ---
  {
    type: "Settings",
    title: "Change Text Generation Model",
    icon: Cpu,
    path: "/settings/models#text",
    keywords: [
      "settings",
      "model",
      "text",
      "text generation",
      "chat",
      "language",
      "llm",
      "text model",
      "content",
      "writing",
      "generation",
      "openai",
      "gpt",
      "ai",
      "assistant",
      "completion",
      "nlp",
      "natural language",
    ],
  },
  {
    type: "Settings",
    title: "Change Vision Model",
    icon: Eye,
    path: "/settings/models#vision",
    keywords: [
      "settings",
      "model",
      "vision",
      "image",
      "ocr",
      "recognition",
      "analysis",
      "picture",
      "photo",
      "sight",
      "scan",
      "visual",
      "image processing",
      "computer vision",
      "ai vision",
      "detect",
      "recognize",
    ],
  },
  {
    type: "Settings",
    title: "Change Decision Model",
    icon: CircuitBoard,
    path: "/settings/models#decision",
    keywords: [
      "settings",
      "model",
      "decision",
      "logic",
      "choices",
      "lightweight",
      "inference",
      "autocomplete",
      "suggestion",
      "recommendation",
      "pipeline",
      "rag",
      "small model",
      "reasoning",
      "ai decision",
      "control",
    ],
  },
  {
    type: "Settings",
    title: "View Installed Models",
    icon: Database,
    path: "/settings/models#installed",
    keywords: [
      "settings",
      "models",
      "installed",
      "available",
      "local",
      "storage",
      "list",
      "installed models",
      "current",
      "existing",
      "downloaded",
      "saved",
      "check models",
      "model list",
      "model manager",
    ],
  },
  {
    type: "Settings",
    title: "Download Recommended Models",
    icon: Download,
    path: "/settings/models#recommended",
    keywords: [
      "settings",
      "models",
      "download",
      "recommended",
      "install",
      "update",
      "fetch",
      "add models",
      "suggested",
      "ai pack",
      "load",
      "import",
      "setup",
      "get models",
      "install models",
    ],
  },
  // --- Security ---
  {
    type: "Settings",
    title: "Change Password",
    icon: KeyRound,
    path: "/settings/security",
    keywords: [
      "settings",
      "password",
      "change",
      "update",
      "reset",
      "credentials",
      "login",
      "security",
      "authentication",
      "auth",
      "key",
      "unlock",
      "passcode",
      "pin",
      "account password",
      "edit password",
      "access",
      "sign in",
      "safety",
      "new password",
    ],
  },
  {
    type: "Settings",
    title: "Delete Account",
    icon: Trash2,
    path: "/settings/security",
    keywords: [
      "settings",
      "delete",
      "account",
      "remove",
      "close",
      "terminate",
      "cancel",
      "end",
      "erase",
      "destroy",
      "remove account",
      "deactivate",
      "disable",
      "forget me",
      "exit",
      "quit",
      "permanent",
      "remove profile",
    ],
  },
  // --- Data ---
  {
    type: "Settings",
    title: "Export Data",
    icon: FileDown,
    path: "/settings/export",
    keywords: [
      "settings",
      "export",
      "data",
      "backup",
      "download",
      "save",
      "copy",
      "files",
      "account data",
      "download data",
      "retrieve",
      "archive",
      "export account",
      "export settings",
      "download info",
      "export files",
    ],
  },
];

export const actionsCommands = [
  {
    type: "Action",
    title: "Create New Journal Entry",
    path: "/journal/new",
    icon: PencilLine,
    keywords: [
      "journal",
      "entry",
      "create",
      "new",
      "add",
      "note",
      "write",
      "record",
      "log",
      "diary",
      "thoughts",
      "memo",
    ],
  },
  {
    type: "Action",
    title: "Go to dashboard",
    path: "/dashboard",
    icon: LayoutDashboardIcon,
    keywords: [
      "dashboard",
      "home",
      "main",
      "overview",
      "summary",
      "stats",
      "start",
      "hub",
      "control panel",
    ],
  },
  {
    type: "Action",
    title: "Open journals",
    path: "/journals",
    icon: BookOpenTextIcon,
    keywords: [
      "journals",
      "entries",
      "notes",
      "view",
      "read",
      "list",
      "logs",
      "diary",
      "history",
      "memories",
      "past",
      "records",
    ],
  },
  {
    type: "Action",
    title: "Chat",
    path: "/chat",
    icon: MessageCirclePlus,
    keywords: [
      "chat",
      "message",
      "talk",
      "conversation",
      "ai",
      "assistant",
      "help",
      "dialogue",
      "support",
      "discussion",
      "ask",
    ],
  },
  {
    type: "Action",
    title: "Create manual goal",
    path: "/goals/create-manual",
    icon: PenSquareIcon,
    keywords: [
      "goal",
      "manual",
      "create",
      "task",
      "objective",
      "plan",
      "set goal",
      "custom goal",
      "add goal",
      "new goal",
    ],
  },
  {
    type: "Action",
    title: "Create goal with AI",
    path: "/goals/create-with-ai",
    icon: MindSageMark,
    keywords: [
      "goal",
      "ai",
      "generate",
      "create",
      "smart",
      "automatic",
      "assistant",
      "objective",
      "plan",
      "ai goal",
      "suggest",
      "recommend",
    ],
  },
  // The two AI setup destinations. Neither is reachable from the dock, and the
  // install guide is only linked from the title-bar status icon, which appears
  // solely when Ollama is missing - so search is the only way back to either.
  {
    type: "Action",
    title: "Install Ollama",
    path: "/ollama-tutorial",
    icon: Rocket,
    keywords: [
      "ollama",
      "install",
      "install ollama",
      "setup ollama",
      "ollama setup",
      "download ollama",
      "tutorial",
      "guide",
      "local ai",
      "local model",
      "llm",
      "ai",
      "offline ai",
      "getting started",
      "how to",
      "terminal",
      "command line",
      "not installed",
      "ollama not found",
    ],
  },
  {
    type: "Action",
    title: "Run AI setup",
    path: "/setup",
    icon: Wand2,
    keywords: [
      "setup",
      "ai setup",
      "onboarding",
      "first run",
      "wizard",
      "install models",
      "download model",
      "pull model",
      "embedding model",
      "generation model",
      "ollama",
      "ai readiness",
      "configure ai",
      "repair setup",
      "re-run setup",
    ],
  },
];
