import {
  CircuitBoard,
  Cpu,
  Database,
  Download,
  Eye,
  FileDown,
  KeyRound,
  Palette,
  Settings2Icon,
  Trash2,
  User,
} from "lucide-react";
import { useNavigate } from "react-router-dom";

export const settingsCommands = [
  // --- Profile ---
  {
    type: "Settings",
    title: "Edit Profile Information",
    icon: User,
    path: "/settings/profile",
    keywords: [
      "profile",
      "edit",
      "update",
      "account",
      "user",
      "info",
      "information",
      "name",
      "username",
      "email",
      "phone",
      "dob",
      "date of birth",
      "details",
      "settings",
      "manage account",
      "change details",
      "preferences",
      "personal",
      "identity",
      "account settings",
    ],
  },
  {
    type: "Settings",
    title: "Change Profile Picture",
    icon: Settings2Icon,
    path: "/settings/profile",
    keywords: [
      "profile",
      "picture",
      "photo",
      "avatar",
      "image",
      "display picture",
      "dp",
      "upload",
      "change photo",
      "update image",
      "set picture",
      "icon",
      "portrait",
      "face",
      "profile image",
      "edit avatar",
    ],
  },
  // --- Themes ---
  {
    type: "Settings",
    title: "Change Theme",
    icon: Palette,
    path: "/settings/theme",
    keywords: [
      "theme",
      "appearance",
      "color",
      "colors",
      "style",
      "look",
      "ui",
      "ux",
      "dark mode",
      "light mode",
      "switch theme",
      "design",
      "palette",
      "skin",
      "mode",
      "background",
      "customize",
      "visuals",
    ],
  },
  // --- Models ---
  {
    type: "Settings",
    title: "Change Text Generation Model",
    icon: Cpu,
    path: "/settings/models#text",
    keywords: [
      "model",
      "text",
      "text generation",
      "chat",
      "language",
      "llm",
      "text model",
      "content",
      "writing",
      "generation",
      "openai",
      "gpt",
      "ai",
      "assistant",
      "completion",
      "nlp",
      "natural language",
    ],
  },
  {
    type: "Settings",
    title: "Change Vision Model",
    icon: Eye,
    path: "/settings/models#vision",
    keywords: [
      "model",
      "vision",
      "image",
      "ocr",
      "recognition",
      "analysis",
      "picture",
      "photo",
      "sight",
      "scan",
      "visual",
      "image processing",
      "computer vision",
      "ai vision",
      "detect",
      "recognize",
    ],
  },
  {
    type: "Settings",
    title: "Change Decision Model",
    icon: CircuitBoard,
    path: "/settings/models#decision",
    keywords: [
      "model",
      "decision",
      "logic",
      "choices",
      "lightweight",
      "inference",
      "autocomplete",
      "suggestion",
      "recommendation",
      "pipeline",
      "rag",
      "small model",
      "reasoning",
      "ai decision",
      "control",
    ],
  },
  {
    type: "Settings",
    title: "View Installed Models",
    icon: Database,
    path: "/settings/models#installed",
    keywords: [
      "models",
      "installed",
      "available",
      "local",
      "storage",
      "list",
      "installed models",
      "current",
      "existing",
      "downloaded",
      "saved",
      "check models",
      "model list",
      "model manager",
    ],
  },
  {
    type: "Settings",
    title: "Download Recommended Models",
    icon: Download,
    path: "/settings/models#recommended",
    keywords: [
      "models",
      "download",
      "recommended",
      "install",
      "update",
      "fetch",
      "add models",
      "suggested",
      "ai pack",
      "load",
      "import",
      "setup",
      "get models",
      "install models",
    ],
  },
  // --- Security ---
  {
    type: "Settings",
    title: "Change Password",
    icon: KeyRound,
    path: "/settings/security",
    keywords: [
      "password",
      "change",
      "update",
      "reset",
      "credentials",
      "login",
      "security",
      "authentication",
      "auth",
      "key",
      "unlock",
      "passcode",
      "pin",
      "account password",
      "edit password",
      "access",
      "sign in",
      "safety",
      "new password",
    ],
  },
  {
    type: "Settings",
    title: "Delete Account",
    icon: Trash2,
    path: "/settings/security",
    keywords: [
      "delete",
      "account",
      "remove",
      "close",
      "terminate",
      "cancel",
      "end",
      "erase",
      "destroy",
      "remove account",
      "deactivate",
      "disable",
      "forget me",
      "exit",
      "quit",
      "permanent",
      "remove profile",
    ],
  },
  // --- Data ---
  {
    type: "Settings",
    title: "Export Data",
    icon: FileDown,
    path: "/settings/export",
    keywords: [
      "export",
      "data",
      "backup",
      "download",
      "save",
      "copy",
      "files",
      "account data",
      "download data",
      "retrieve",
      "archive",
      "export account",
      "export settings",
      "download info",
      "export files",
    ],
  },
];
